//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.currenda.pl/epu")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.currenda.pl/epu", IsNullable=false)]
public partial class Types {
    
    private typRodzajCzynnosci alaField;
    
    /// <remarks/>
    public typRodzajCzynnosci ala {
        get {
            return this.alaField;
        }
        set {
            this.alaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public enum typRodzajCzynnosci {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("podjęcie postępowania egzekucyjnego")]
    podjęciepostępowaniaegzekucyjnego,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("koszty egzekucyjne poniesione przez wierzyciela")]
    kosztyegzekucyjneponiesioneprzezwierzyciela,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("umorzono przez wyegzekwowanie w całości")]
    umorzonoprzezwyegzekwowaniewcałości,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("umorzono przez wyegzekwowanie w części")]
    umorzonoprzezwyegzekwowaniewczęści,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("umorzono w inny sposób")]
    umorzonowinnysposób,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("zwrot wniosku")]
    zwrotwniosku,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("przekazano sprawę")]
    przekazanosprawę,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typDowod {
    
    private string faktStwierdzanyField;
    
    private string opisField;
    
    private sbyte numerField;
    
    private typRodzajDowodu typDowoduField;
    
    private string oznaczenieField;
    
    private string dataDowoduField;
    
    /// <remarks/>
    public string FaktStwierdzany {
        get {
            return this.faktStwierdzanyField;
        }
        set {
            this.faktStwierdzanyField = value;
        }
    }
    
    /// <remarks/>
    public string Opis {
        get {
            return this.opisField;
        }
        set {
            this.opisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte numer {
        get {
            return this.numerField;
        }
        set {
            this.numerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public typRodzajDowodu typDowodu {
        get {
            return this.typDowoduField;
        }
        set {
            this.typDowoduField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string oznaczenie {
        get {
            return this.oznaczenieField;
        }
        set {
            this.oznaczenieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataDowodu {
        get {
            return this.dataDowoduField;
        }
        set {
            this.dataDowoduField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public enum typRodzajDowodu {
    
    /// <remarks/>
    inny,
    
    /// <remarks/>
    umowa,
    
    /// <remarks/>
    faktura,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("akt notarialny")]
    aktnotarialny,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typOkresOdsetkowy {
    
    private string opisField;
    
    private string dataOdField;
    
    private string dataDoField;
    
    private decimal kwotaField;
    
    private bool kwotaFieldSpecified;
    
    private sbyte czyUstawoweField;
    
    private decimal stopaField;
    
    private bool stopaFieldSpecified;
    
    private sbyte okresField;
    
    private bool okresFieldSpecified;
    
    private sbyte odWniesieniaField;
    
    private bool odWniesieniaFieldSpecified;
    
    private sbyte doZaplatyField;
    
    private bool doZaplatyFieldSpecified;
    
    /// <remarks/>
    public string Opis {
        get {
            return this.opisField;
        }
        set {
            this.opisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataOd {
        get {
            return this.dataOdField;
        }
        set {
            this.dataOdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataDo {
        get {
            return this.dataDoField;
        }
        set {
            this.dataDoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal kwota {
        get {
            return this.kwotaField;
        }
        set {
            this.kwotaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool kwotaSpecified {
        get {
            return this.kwotaFieldSpecified;
        }
        set {
            this.kwotaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte czyUstawowe {
        get {
            return this.czyUstawoweField;
        }
        set {
            this.czyUstawoweField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal stopa {
        get {
            return this.stopaField;
        }
        set {
            this.stopaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool stopaSpecified {
        get {
            return this.stopaFieldSpecified;
        }
        set {
            this.stopaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte okres {
        get {
            return this.okresField;
        }
        set {
            this.okresField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool okresSpecified {
        get {
            return this.okresFieldSpecified;
        }
        set {
            this.okresFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte odWniesienia {
        get {
            return this.odWniesieniaField;
        }
        set {
            this.odWniesieniaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool odWniesieniaSpecified {
        get {
            return this.odWniesieniaFieldSpecified;
        }
        set {
            this.odWniesieniaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte doZaplaty {
        get {
            return this.doZaplatyField;
        }
        set {
            this.doZaplatyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool doZaplatySpecified {
        get {
            return this.doZaplatyFieldSpecified;
        }
        set {
            this.doZaplatyFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typRoszczenie {
    
    private typOkresOdsetkowy[] odsetkiField;
    
    private sbyte[] dowodyField;
    
    private int numerField;
    
    private decimal wartoscField;
    
    private typWaluta walutaField;
    
    private string opisField;
    
    private sbyte odsetkiField1;
    
    private sbyte solidarnieField;
    
    private sbyte typField;
    
    private string dataWymagalnosciField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("OkresOdsetkowy", IsNullable=false)]
    public typOkresOdsetkowy[] Odsetki {
        get {
            return this.odsetkiField;
        }
        set {
            this.odsetkiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Dowod", IsNullable=false)]
    public sbyte[] Dowody {
        get {
            return this.dowodyField;
        }
        set {
            this.dowodyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int numer {
        get {
            return this.numerField;
        }
        set {
            this.numerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal wartosc {
        get {
            return this.wartoscField;
        }
        set {
            this.wartoscField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public typWaluta waluta {
        get {
            return this.walutaField;
        }
        set {
            this.walutaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string opis {
        get {
            return this.opisField;
        }
        set {
            this.opisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte odsetki {
        get {
            return this.odsetkiField1;
        }
        set {
            this.odsetkiField1 = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte solidarnie {
        get {
            return this.solidarnieField;
        }
        set {
            this.solidarnieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte typ {
        get {
            return this.typField;
        }
        set {
            this.typField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataWymagalnosci {
        get {
            return this.dataWymagalnosciField;
        }
        set {
            this.dataWymagalnosciField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public enum typWaluta {
    
    /// <remarks/>
    PLN,
    
    /// <remarks/>
    USD,
    
    /// <remarks/>
    EUR,
    
    /// <remarks/>
    CHF,
    
    /// <remarks/>
    GBP,
    
    /// <remarks/>
    AUD,
    
    /// <remarks/>
    CAD,
    
    /// <remarks/>
    CZK,
    
    /// <remarks/>
    DKK,
    
    /// <remarks/>
    HUF,
    
    /// <remarks/>
    JPY,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typRachunekDoZwrotuOplat {
    
    private string numerRachunkuDoZwrotuOplatField;
    
    private string wlascicielRachunkuField;
    
    /// <remarks/>
    public string NumerRachunkuDoZwrotuOplat {
        get {
            return this.numerRachunkuDoZwrotuOplatField;
        }
        set {
            this.numerRachunkuDoZwrotuOplatField = value;
        }
    }
    
    /// <remarks/>
    public string WlascicielRachunku {
        get {
            return this.wlascicielRachunkuField;
        }
        set {
            this.wlascicielRachunkuField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typKoszty {
    
    private decimal wartoscField;
    
    private sbyte zasadzenieField;
    
    private sbyte wgNormField;
    
    private string opisField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal wartosc {
        get {
            return this.wartoscField;
        }
        set {
            this.wartoscField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte zasadzenie {
        get {
            return this.zasadzenieField;
        }
        set {
            this.zasadzenieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte wgNorm {
        get {
            return this.wgNormField;
        }
        set {
            this.wgNormField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string opis {
        get {
            return this.opisField;
        }
        set {
            this.opisField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typOplata {
    
    private bool obnizenieKosztowOplatySadowejField;
    
    private bool obnizenieKosztowOplatySadowejFieldSpecified;
    
    private decimal wartoscField;
    
    private sbyte zwolnienieField;
    
    private sbyte zasadzenieField;
    
    private ulong identyfikatorField;
    
    private bool identyfikatorFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ObnizenieKosztowOplatySadowej {
        get {
            return this.obnizenieKosztowOplatySadowejField;
        }
        set {
            this.obnizenieKosztowOplatySadowejField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ObnizenieKosztowOplatySadowejSpecified {
        get {
            return this.obnizenieKosztowOplatySadowejFieldSpecified;
        }
        set {
            this.obnizenieKosztowOplatySadowejFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal wartosc {
        get {
            return this.wartoscField;
        }
        set {
            this.wartoscField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte zwolnienie {
        get {
            return this.zwolnienieField;
        }
        set {
            this.zwolnienieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte zasadzenie {
        get {
            return this.zasadzenieField;
        }
        set {
            this.zasadzenieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong identyfikator {
        get {
            return this.identyfikatorField;
        }
        set {
            this.identyfikatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool identyfikatorSpecified {
        get {
            return this.identyfikatorFieldSpecified;
        }
        set {
            this.identyfikatorFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typInnyRejestr {
    
    private string typField;
    
    private string organField;
    
    private string numerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string typ {
        get {
            return this.typField;
        }
        set {
            this.typField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string organ {
        get {
            return this.organField;
        }
        set {
            this.organField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string numer {
        get {
            return this.numerField;
        }
        set {
            this.numerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typInstytucja {
    
    private string nazwaField;
    
    private string siedzibaField;
    
    private string rEGONField;
    
    private sbyte czyRejestrField;
    
    private object itemField;
    
    private typOsoba[] listaZarzaduField;
    
    /// <remarks/>
    public string Nazwa {
        get {
            return this.nazwaField;
        }
        set {
            this.nazwaField = value;
        }
    }
    
    /// <remarks/>
    public string Siedziba {
        get {
            return this.siedzibaField;
        }
        set {
            this.siedzibaField = value;
        }
    }
    
    /// <remarks/>
    public string REGON {
        get {
            return this.rEGONField;
        }
        set {
            this.rEGONField = value;
        }
    }
    
    /// <remarks/>
    public sbyte czyRejestr {
        get {
            return this.czyRejestrField;
        }
        set {
            this.czyRejestrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InnyRejestr", typeof(typInnyRejestr))]
    [System.Xml.Serialization.XmlElementAttribute("KRS", typeof(string))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CzlonekZarzadu", IsNullable=false)]
    public typOsoba[] ListaZarzadu {
        get {
            return this.listaZarzaduField;
        }
        set {
            this.listaZarzaduField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typOsoba {
    
    private string imieField;
    
    private string imie2Field;
    
    private string nazwiskoField;
    
    private string pESELField;
    
    private string stanowiskoField;
    
    /// <remarks/>
    public string Imie {
        get {
            return this.imieField;
        }
        set {
            this.imieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Imie2 {
        get {
            return this.imie2Field;
        }
        set {
            this.imie2Field = value;
        }
    }
    
    /// <remarks/>
    public string Nazwisko {
        get {
            return this.nazwiskoField;
        }
        set {
            this.nazwiskoField = value;
        }
    }
    
    /// <remarks/>
    public string PESEL {
        get {
            return this.pESELField;
        }
        set {
            this.pESELField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string stanowisko {
        get {
            return this.stanowiskoField;
        }
        set {
            this.stanowiskoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typOsobaFizyczna {
    
    private string imieField;
    
    private string imie2Field;
    
    private string nazwiskoField;
    
    private string nazwaField;
    
    private string pESELField;
    
    private string nrDokumentuField;
    
    private string imieOjcaField;
    
    private string imieMatkiField;
    
    private string nazwiskoRodoweField;
    
    private string nazwiskoRodoweMatkiField;
    
    private string miejsceUrodzeniaField;
    
    private string dataUrodzeniaField;
    
    /// <remarks/>
    public string Imie {
        get {
            return this.imieField;
        }
        set {
            this.imieField = value;
        }
    }
    
    /// <remarks/>
    public string Imie2 {
        get {
            return this.imie2Field;
        }
        set {
            this.imie2Field = value;
        }
    }
    
    /// <remarks/>
    public string Nazwisko {
        get {
            return this.nazwiskoField;
        }
        set {
            this.nazwiskoField = value;
        }
    }
    
    /// <remarks/>
    public string Nazwa {
        get {
            return this.nazwaField;
        }
        set {
            this.nazwaField = value;
        }
    }
    
    /// <remarks/>
    public string PESEL {
        get {
            return this.pESELField;
        }
        set {
            this.pESELField = value;
        }
    }
    
    /// <remarks/>
    public string NrDokumentu {
        get {
            return this.nrDokumentuField;
        }
        set {
            this.nrDokumentuField = value;
        }
    }
    
    /// <remarks/>
    public string ImieOjca {
        get {
            return this.imieOjcaField;
        }
        set {
            this.imieOjcaField = value;
        }
    }
    
    /// <remarks/>
    public string ImieMatki {
        get {
            return this.imieMatkiField;
        }
        set {
            this.imieMatkiField = value;
        }
    }
    
    /// <remarks/>
    public string NazwiskoRodowe {
        get {
            return this.nazwiskoRodoweField;
        }
        set {
            this.nazwiskoRodoweField = value;
        }
    }
    
    /// <remarks/>
    public string NazwiskoRodoweMatki {
        get {
            return this.nazwiskoRodoweMatkiField;
        }
        set {
            this.nazwiskoRodoweMatkiField = value;
        }
    }
    
    /// <remarks/>
    public string MiejsceUrodzenia {
        get {
            return this.miejsceUrodzeniaField;
        }
        set {
            this.miejsceUrodzeniaField = value;
        }
    }
    
    /// <remarks/>
    public string DataUrodzenia {
        get {
            return this.dataUrodzeniaField;
        }
        set {
            this.dataUrodzeniaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typStrona {
    
    private string obcokrajowiecStringField;
    
    private bool obcokrajowiecField;
    
    private bool brakNumerowIdentyfikacyjnychField;
    
    private sbyte reprezentacjaField;
    
    private sbyte rodzajStronyField;
    
    private object itemField;
    
    private string nIPField;
    
    private typAdres adresField;
    
    private string numerKontaField;
    
    private ulong idField;
    
    /// <remarks/>
    public string ObcokrajowiecString {
        get {
            return this.obcokrajowiecStringField;
        }
        set {
            this.obcokrajowiecStringField = value;
        }
    }
    
    /// <remarks/>
    public bool Obcokrajowiec {
        get {
            return this.obcokrajowiecField;
        }
        set {
            this.obcokrajowiecField = value;
        }
    }
    
    /// <remarks/>
    public bool BrakNumerowIdentyfikacyjnych {
        get {
            return this.brakNumerowIdentyfikacyjnychField;
        }
        set {
            this.brakNumerowIdentyfikacyjnychField = value;
        }
    }
    
    /// <remarks/>
    public sbyte reprezentacja {
        get {
            return this.reprezentacjaField;
        }
        set {
            this.reprezentacjaField = value;
        }
    }
    
    /// <remarks/>
    public sbyte rodzajStrony {
        get {
            return this.rodzajStronyField;
        }
        set {
            this.rodzajStronyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Instytucja", typeof(typInstytucja))]
    [System.Xml.Serialization.XmlElementAttribute("OsobaFizyczna", typeof(typOsobaFizyczna))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    public string NIP {
        get {
            return this.nIPField;
        }
        set {
            this.nIPField = value;
        }
    }
    
    /// <remarks/>
    public typAdres Adres {
        get {
            return this.adresField;
        }
        set {
            this.adresField = value;
        }
    }
    
    /// <remarks/>
    public string numerKonta {
        get {
            return this.numerKontaField;
        }
        set {
            this.numerKontaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typAdres {
    
    private string ulicaField;
    
    private string nr_domuField;
    
    private string nr_mieszkaniaField;
    
    private string kodField;
    
    private string miejscowoscField;
    
    private string pocztaField;
    
    private string krajField;
    
    private string wojewodztwoField;
    
    private string powiatField;
    
    private string gminaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ulica {
        get {
            return this.ulicaField;
        }
        set {
            this.ulicaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nr_domu {
        get {
            return this.nr_domuField;
        }
        set {
            this.nr_domuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nr_mieszkania {
        get {
            return this.nr_mieszkaniaField;
        }
        set {
            this.nr_mieszkaniaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string kod {
        get {
            return this.kodField;
        }
        set {
            this.kodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string miejscowosc {
        get {
            return this.miejscowoscField;
        }
        set {
            this.miejscowoscField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string poczta {
        get {
            return this.pocztaField;
        }
        set {
            this.pocztaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string kraj {
        get {
            return this.krajField;
        }
        set {
            this.krajField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string wojewodztwo {
        get {
            return this.wojewodztwoField;
        }
        set {
            this.wojewodztwoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string powiat {
        get {
            return this.powiatField;
        }
        set {
            this.powiatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string gmina {
        get {
            return this.gminaField;
        }
        set {
            this.gminaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typSkladajacy {
    
    private typOsoba osobaField;
    
    private string nazwaField;
    
    private typAdres adresField;
    
    private sbyte pelnomocnikField;
    
    private string podstawaField;
    
    /// <remarks/>
    public typOsoba Osoba {
        get {
            return this.osobaField;
        }
        set {
            this.osobaField = value;
        }
    }
    
    /// <remarks/>
    public string Nazwa {
        get {
            return this.nazwaField;
        }
        set {
            this.nazwaField = value;
        }
    }
    
    /// <remarks/>
    public typAdres Adres {
        get {
            return this.adresField;
        }
        set {
            this.adresField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte pelnomocnik {
        get {
            return this.pelnomocnikField;
        }
        set {
            this.pelnomocnikField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string podstawa {
        get {
            return this.podstawaField;
        }
        set {
            this.podstawaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typAdresat {
    
    private string nazwaField;
    
    private string wydzialField;
    
    private typAdres adresField;
    
    private ulong idField;
    
    /// <remarks/>
    public string Nazwa {
        get {
            return this.nazwaField;
        }
        set {
            this.nazwaField = value;
        }
    }
    
    /// <remarks/>
    public string Wydzial {
        get {
            return this.wydzialField;
        }
        set {
            this.wydzialField = value;
        }
    }
    
    /// <remarks/>
    public typAdres Adres {
        get {
            return this.adresField;
        }
        set {
            this.adresField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class PozewEPU {
    
    private string oswiadczenieField;
    
    private typAdresat adresatField;
    
    private typAdresat sadWlasciwyField;
    
    private typSkladajacy osobaSkladajacaField;
    
    private typStrona[] listaPowodowField;
    
    private typStrona[] listaPozwanychField;
    
    private string sprawaWgPowodaField;
    
    private decimal wartoscSporuField;
    
    private typOplata oplataSadowaField;
    
    private typKoszty kosztyZastepstwaField;
    
    private typKoszty inneKosztyField;
    
    private typRachunekDoZwrotuOplat rachunekDoZwrotuOplatField;
    
    private typRoszczenie[] listaRoszczenField;
    
    private typDowod[] listaDowodowField;
    
    private string inneRoszczeniaField;
    
    private string uzasadnienieField;
    
    private ulong idField;
    
    private string versionField;
    
    private string dataZlozeniaField;
    
    public PozewEPU() {
        this.versionField = "1.0";
    }
    
    /// <remarks/>
    public string Oswiadczenie {
        get {
            return this.oswiadczenieField;
        }
        set {
            this.oswiadczenieField = value;
        }
    }
    
    /// <remarks/>
    public typAdresat Adresat {
        get {
            return this.adresatField;
        }
        set {
            this.adresatField = value;
        }
    }
    
    /// <remarks/>
    public typAdresat SadWlasciwy {
        get {
            return this.sadWlasciwyField;
        }
        set {
            this.sadWlasciwyField = value;
        }
    }
    
    /// <remarks/>
    public typSkladajacy OsobaSkladajaca {
        get {
            return this.osobaSkladajacaField;
        }
        set {
            this.osobaSkladajacaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Powod", IsNullable=false)]
    public typStrona[] ListaPowodow {
        get {
            return this.listaPowodowField;
        }
        set {
            this.listaPowodowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Pozwany", IsNullable=false)]
    public typStrona[] ListaPozwanych {
        get {
            return this.listaPozwanychField;
        }
        set {
            this.listaPozwanychField = value;
        }
    }
    
    /// <remarks/>
    public string SprawaWgPowoda {
        get {
            return this.sprawaWgPowodaField;
        }
        set {
            this.sprawaWgPowodaField = value;
        }
    }
    
    /// <remarks/>
    public decimal WartoscSporu {
        get {
            return this.wartoscSporuField;
        }
        set {
            this.wartoscSporuField = value;
        }
    }
    
    /// <remarks/>
    public typOplata OplataSadowa {
        get {
            return this.oplataSadowaField;
        }
        set {
            this.oplataSadowaField = value;
        }
    }
    
    /// <remarks/>
    public typKoszty KosztyZastepstwa {
        get {
            return this.kosztyZastepstwaField;
        }
        set {
            this.kosztyZastepstwaField = value;
        }
    }
    
    /// <remarks/>
    public typKoszty InneKoszty {
        get {
            return this.inneKosztyField;
        }
        set {
            this.inneKosztyField = value;
        }
    }
    
    /// <remarks/>
    public typRachunekDoZwrotuOplat RachunekDoZwrotuOplat {
        get {
            return this.rachunekDoZwrotuOplatField;
        }
        set {
            this.rachunekDoZwrotuOplatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Roszczenie", IsNullable=false)]
    public typRoszczenie[] ListaRoszczen {
        get {
            return this.listaRoszczenField;
        }
        set {
            this.listaRoszczenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Dowod", IsNullable=false)]
    public typDowod[] ListaDowodow {
        get {
            return this.listaDowodowField;
        }
        set {
            this.listaDowodowField = value;
        }
    }
    
    /// <remarks/>
    public string InneRoszczenia {
        get {
            return this.inneRoszczeniaField;
        }
        set {
            this.inneRoszczeniaField = value;
        }
    }
    
    /// <remarks/>
    public string Uzasadnienie {
        get {
            return this.uzasadnienieField;
        }
        set {
            this.uzasadnienieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataZlozenia {
        get {
            return this.dataZlozeniaField;
        }
        set {
            this.dataZlozeniaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.currenda.pl/epu")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.currenda.pl/epu", IsNullable=false)]
public partial class Pozwy {
    
    private PozewEPU[] pozewEPUField;
    
    private string oznaczeniePaczkiField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PozewEPU")]
    public PozewEPU[] PozewEPU {
        get {
            return this.pozewEPUField;
        }
        set {
            this.pozewEPUField = value;
        }
    }

    [System.Xml.Serialization.XmlAttributeAttribute(Namespace = "http://www.w3.org/2000/xmlns/")]
    public string curr
    {
        get { return "http://www.currenda.pl/epu"; }
        set { }
    }


    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OznaczeniePaczki {
        get {
            return this.oznaczeniePaczkiField;
        }
        set {
            this.oznaczeniePaczkiField = value;
        }
    }
}
